### ISSUE TITLE
Logo offer for PageReloader

### ISSUE THREAD

**Issue by familqasimov** [SloCompTech/PageReloader#1]
Hi old friend. I would like to offer logo. I can give you all the formats of the design free. If you want a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/41932667-a1a315aa-7992-11e8-909e-d74c39337858.png)

Best regard

**Comment by SloCompTech** [comment]
Nice logo, would you be able to put it in different sizes and put it in `img` and link icon to the page ?

**Comment by familqasimov** [comment]
Hi. Please write me, what color logo variation are you like.
Good luck....

**Comment by SloCompTech** [comment]
I really like 2nd logo from the left (blue & white).

**Comment by familqasimov** [comment]
Please click here to view all files: https://drive.google.com/drive/folders/1daTvkFiKJb7LZzBPaEvTivGNiCU_gg4w?ogsrc=32

**Comment by familqasimov** [comment]
Can I sent PR for logo?

**Comment by SloCompTech** [comment]
Yes of course
